### ISSUE TITLE
Better Report Metrics Tracking

### ISSUE THREAD

**Issue by hellsan631** [hellsan631/Email-Security-Check#33]
This includes tracking of several key variables in each report

- [x] Score of email
- [x] Score of domain
- [x] Domain averages
- [ ] Global averages

Proposed is the creation of 3 new models to handle the above data sets. 

- [x] __Score__ - holds a single reports score card minus any weighting
- [x] __Domain__ - represents a connection between a score and a specific domain
- [x] __Aggregate__ - embedded object inside of a domain/email which represents an average of all scores for that email/domain

Proposed is the creation of new API endpoints which generate aggregate scoring for global domains.

- [ ] __Aggregate__ - _getGlobalAggregate_
